# Generated by Django 5.1.7 on 2025-03-16 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ijajat_no', models.CharField(max_length=50)),
                ('vehicle_no', models.CharField(max_length=100)),
                ('chassis_no', models.CharField(max_length=100)),
                ('engine_no', models.CharField(max_length=100)),
                ('insuranceDate', models.DateField()),
                ('vehicleFitnessTestDate', models.DateField()),
                ('issueDate', models.DateField(auto_now=True)),
                ('expiryDate', models.DateField()),
                ('isChange', models.BooleanField(default=False)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.route')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.vehicletype')),
            ],
        ),
    ]
