# Generated by Django 5.1.7 on 2025-03-16 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicles',
            old_name='isChange',
            new_name='isRouteChange',
        ),
    ]
