# Generated by Django 5.1.7 on 2025-03-16 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_rename_ischange_vehicles_isroutechange'),
    ]

    operations = [
        migrations.CreateModel(
            name='YatayatSewa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('registeredDate', models.DateField()),
                ('expiryDate', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='vehicles',
            name='vehicleOwner',
            field=models.CharField(default='Ram', max_length=200),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='yatayat_sewa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='route.yatayatsewa'),
        ),
    ]
