# Generated by Django 5.1.7 on 2025-03-16 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0003_yatayatsewa_vehicles_vehicleowner_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehicles',
            new_name='Vehicle',
        ),
    ]
