# Generated by Django 5.1.7 on 2025-03-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0004_rename_vehicles_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='isRenew',
            field=models.BooleanField(default=False),
        ),
    ]
