# Generated by Django 5.1.7 on 2025-03-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0005_vehicle_isrenew'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='rajaswo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
